### ISSUE TITLE
The line if asset["asset-id"] == asset_index && asset["amount"] == 1: always returns false for reasons stated below and so It's bad code

### ISSUE THREAD

**Issue by Sam2much96** [lucasvanmol/algodot#5] opened 2022-07-25 20:45 UTC
In the context that this is an automated test script for GIthub actions, i have questions about the above line of code

(1) The assets are created but even when creating new tokens, the asset id and the asset index aren't equal, even though running the script ./sandbox goal asset info --assetid shows that the asset was created. For example, i manipulated the script to create new tokens called GameTestTokens, with a Unit name of GTC, 
checking the asset info on the sandbox returns

Asset ID:         111
Creator:          L5ESENBL23J2GJGM64Y767IXWGBCKXMGS2OGZ3MC5BBGWJAKJJAUK7BJK4
Asset name:       GameTestCoin

Unit name:        GTC

Maximum issue:    1000.00 GTC
Reserve amount:   1000.00 GTC
Issued:           0.00 GTC
Decimals:         2
Default frozen:   false
Manager address:  
Reserve address:  L5ESENBL23J2GJGM64Y767IXWGBCKXMGS2OGZ3MC5BBGWJAKJJAUK7BJK4 (Empty. Defaulting to creator)
Freeze address:   
Clawback address:

So even though it's an entirely new token, the condition asset["asset-id"] == asset_index would return false

(2) The asset creation functions creates TestCoin tokens with 1,000 amount by default so the condition  asset["amount"] == 1: would always return false and that's from the initial asset creation function, not from anything else

(3) Even though i created the asset using funder account YBGKX36PRRWQEPPLMWOAAX4M7HILOAX4WJW52HS2TF6ATSBUOGLQTJMKU4
sandbox analysis shows the asset creator as, and the reserve address
L5ESENBL23J2GJGM64Y767IXWGBCKXMGS2OGZ3MC5BBGWJAKJJAUK7BJK4

why is this? it seems odd.

**Comment by Sam2much96** [comment] 2022-07-25 20:50
A much better conditional would be to check if the asset id returns null, and if it's not null, return true. Then include a line for printing out the asset details when exiting the code bloc

if asset["asset-id"] && asset_index && asset["amount"] != null:
  return true
print ("Asset Id : ",asset["asset-id"], "//", " Asset Index: ", asset_index,"//", "Asset Amount: ",asset["amount"]) #for debug purposes only

**Comment by Sam2much96** [comment] 2022-07-25 20:56
For my test code for GameTestCoin, 
Asset Id: 48
Asset Index: 111

condition 1 fails automatically

Asset amount: 100000

condition 2 fails automatically

And both conditionals need to be true for the function to return true, thus dooming the entire line to boarder line failure, except there's something else I'm missing. Please enlighten me on your thought process dev

**Comment by Sam2much96** [comment] 2022-07-25 21:14
> In the context that this is an automated test script for GIthub actions, i have questions about the above line of code
> 
> (1) The assets are created but even when creating new tokens, the asset id and the asset index aren't equal, even though running the script ./sandbox goal asset info --assetid shows that the asset was created. For example, i manipulated the script to create new tokens called GameTestTokens, with a Unit name of GTC, checking the asset info on the sandbox returns
> 
> Asset ID: 111 Creator: L5ESENBL23J2GJGM64Y767IXWGBCKXMGS2OGZ3MC5BBGWJAKJJAUK7BJK4 Asset name: GameTestCoin
> 
> Unit name: GTC
> 
> Maximum issue: 1000.00 GTC Reserve amount: 1000.00 GTC Issued: 0.00 GTC Decimals: 2 Default frozen: false Manager address: Reserve address: L5ESENBL23J2GJGM64Y767IXWGBCKXMGS2OGZ3MC5BBGWJAKJJAUK7BJK4 (Empty. Defaulting to creator) Freeze address: Clawback address:
> 
> So even though it's an entirely new token, the condition asset["asset-id"] == asset_index would return false
> 
> (2) The asset creation functions creates TestCoin tokens with 1,000 amount by default so the condition asset["amount"] == 1: would always return false and that's from the initial asset creation function, not from anything else
> 
> (3) Even though i created the asset using funder account YBGKX36PRRWQEPPLMWOAAX4M7HILOAX4WJW52HS2TF6ATSBUOGLQTJMKU4 sandbox analysis shows the asset creator as, and the reserve address L5ESENBL23J2GJGM64Y767IXWGBCKXMGS2OGZ3MC5BBGWJAKJJAUK7BJK4
> 
> why is this? it seems odd.

The creator account was my default sandbox account. So the tx ignored the funder's account variable in and just used the default sandbox account as the creator

	tx = algod.construct_asset_create( 
		params,
		funder_address, # Creator
		"GameTestCoin",	# Asset name
		2,			# Decimals #i.e how many decimals from the total supply
		false,		# Default frozen?
		100000,		# Total supply # This is 1000.00
		"GTC"		# Unit name
	)

**Comment by Sam2much96** [comment] 2022-07-26 04:44
Final Conclusion:

Upon further testing, if asset["asset-id"] == asset_index && asset["amount"] == 1: return true only returns true if the following conditions are met

(1) Both the funder and reciever account should not have the assets created prior to reaching that conditional, so the code shouldn't have been run before and failed on 2 of the same addresses. Which makes sense when you're using newly generated accounts, but not if you're testing on already created accounts

(2) asset["amount"] has to be set to the asset's Total supply

(3) printerr("   !! _test_asset_transfers failed") doesn't really explain much. Including a debug line before printing out the error makes it easier to understand that the function didn't really fail, it worked but the condition to return true is a slippery slope

including the line below instead makes the code more easier to read, more self explanatory, and includes a debug of the failure

printerr ("!! _test_asset_transfers failed" ,"Asset Id :",asset["asset-id"], "//", " Asset Index: ", asset_index,"//", "Asset Amount: ",asset["amount"])

please include that instead of printerr("   !! _test_asset_transfers failed"), so it's easier to debug why the transfer failed, and if the assets where indeed created. It save users alot of time !

**Comment by Sam2much96** [comment] 2022-07-26 04:50
> In the context that this is an automated test script for GIthub actions, i have questions about the above line of code
> 
> (1) The assets are created but even when creating new tokens, the asset id and the asset index aren't equal, even though running the script ./sandbox goal asset info --assetid shows that the asset was created. For example, i manipulated the script to create new tokens called GameTestTokens, with a Unit name of GTC, checking the asset info on the sandbox returns
> 
> Asset ID: 111 Creator: L5ESENBL23J2GJGM64Y767IXWGBCKXMGS2OGZ3MC5BBGWJAKJJAUK7BJK4 Asset name: GameTestCoin
> 
> Unit name: GTC
> 
> Maximum issue: 1000.00 GTC Reserve amount: 1000.00 GTC Issued: 0.00 GTC Decimals: 2 Default frozen: false Manager address: Reserve address: L5ESENBL23J2GJGM64Y767IXWGBCKXMGS2OGZ3MC5BBGWJAKJJAUK7BJK4 (Empty. Defaulting to creator) Freeze address: Clawback address:
> 
> So even though it's an entirely new token, the condition asset["asset-id"] == asset_index would return false
> 
> (2) The asset creation functions creates TestCoin tokens with 1,000 amount by default so the condition asset["amount"] == 1: would always return false and that's from the initial asset creation function, not from anything else
> 
> (3) Even though i created the asset using funder account YBGKX36PRRWQEPPLMWOAAX4M7HILOAX4WJW52HS2TF6ATSBUOGLQTJMKU4 sandbox analysis shows the asset creator as, and the reserve address L5ESENBL23J2GJGM64Y767IXWGBCKXMGS2OGZ3MC5BBGWJAKJJAUK7BJK4
> 
> why is this? it seems odd.

This error was caused by using a closed function to create assets so my sandbox environment used a default account i'd saved to a variable earlier instead of the funder's address. I fixed it by feeding the asset creation parameters directly into the function

func create_assets( address : String): 
	print("-----creating asset----")
	tx = algod.construct_asset_create( 
		params,
		address, # Creator #SDK uses default sandbox wallet and ignores this creator (fixed)
		"GameTestCoin",	# Asset name
		2,			# Decimals #i.e how many decimals from the total supply
		false,		# Default frozen?
		100000,		# Total supply # This is 1000.00
		"GTC"		# Unit name
	)
	return tx

that stopped the error from repeating itself. It might be something unique to my sandbox environment though, not a general error in the function itself. seeing as how the game engine can randomly grab environment variables, seems like a better way to prevent accidental bugs

**Comment by lucasvanmol** [comment] 2022-07-26 10:24
I think you're misunderstanding the point of the code test code. It's only meant to be run on a fresh sandbox with a specific configuration. Let me go through your points:

> (1) Both the funder and reciever account should not have the assets created prior to reaching that conditional, so the code shouldn't have been run before and failed on 2 of the same addresses. Which makes sense when you're using newly generated accounts, but not if you're testing on already created accounts

This code is meant to be run in a testing environment by spinning up a sandbox node with the proper configuration (you can see the configuration in the test directory). As such it may fail when using a node that isn't configured the way it expects or has already been running for a while

> (2) asset["amount"] has to be set to the asset's Total supply

This isn't true, it's checking for how much of the created asset (created at [this line](https://github.com/lucasvanmol/algodot/blob/4404defb8f4bfe26fcbc91f5009edf2f371ce1ed/test/project/main.gd#L91)) is being transferred to the `funder_address` account. Because of the asset transfer transaction created at [this line](https://github.com/lucasvanmol/algodot/blob/4404defb8f4bfe26fcbc91f5009edf2f371ce1ed/test/project/main.gd#L113) the amount transferred should always be one.

> (3) printerr(" !! _test_asset_transfers failed") doesn't really explain much. Including a debug line before printing out the error makes it easier to understand that the function didn't really fail, it worked but the condition to return true is a slippery slope

I'm not sure I agree. If the tests are run as they should then all the tests pass, so no need to print out any debug information. If the same test fails in the future due to some regression, then it would warrant some further investigation/debugging.

> including the line below instead makes the code more easier to read, more self explanatory, and includes a debug of the failure
>
> printerr ("!! _test_asset_transfers failed" ,"Asset Id :",asset["asset-id"], "//", " Asset Index: ", asset_index,"//", "Asset Amount: ",asset["amount"])

I think this would be more suited to use in a sort of example/usage tutorial. That's definitely missing still from this repo

**Closed as completed by lucasvanmol** 2022-07-26 10:24 UTC

**Comment by Sam2much96** [comment] 2022-07-27 05:03
You're right.
I thought of originally combining both my code and yours in a single .gd script, but it'll just create a convoluted mess. 
Your code is very professional and efficient, My code is Dumb and Human Readable.
I'll separate my changes into a new script called Algod.gd so it's not confused with main.gd . 
Future user can implement functions and changes from Algod.gd without messing up your automated test.

**Comment by Sam2much96** [comment] 2022-07-27 06:14
So, 

var asset_tx = algod.construct_asset_xfer(
		params,
		account[0],
		funder_address,
		1,
		asset_index
	)

transfers 1 TestCoin from account[0] to the funder's account, then ...&& asset["amount"] checks if that 1 Testcoin is present in the funder_address.

Thanks for clearing that up for me. I wrote my code the other way around. My code makes the funder_address create the tokens then checks for the Total supply of TestCoins in the funder_address. 
My bad, i'll make changes. Thanks for clearing that up for me
